### ISSUE TITLE
enMuteGroupMute Description

### ISSUE THREAD

**Issue by graywolf336** [muffeeee/midas-pro-series-osc-commands#3]
https://github.com/muffeeee/midas-pro-series-osc-commands/blob/808f3c974bfa9b7a33b34eefe82153540e02c5c0/pro-series-endpoints.json#L20095-L20100

This toggles the mute groups to be muted or unmuted.

`/enPPCSwitchMessage/enVirtualMuteGroups/enMuteGroupMute/${ muteGroupIndex }`

The mute group index is zero based like the other inputs. The Pro2 only responds to a value of `1` being passed in, zero does nothing.

I would create a PR for this, but I'm not presently at a place I can.

**Comment by muffeeee** [comment]
Thanks for the info!

Don't worry about a PR, I'll add this as soon as I am able to.

tir. 17. jan. 2023 kl. 21:42 skrev Bradley Hilton ***@***.***
