### ISSUE TITLE
Listed OSC Commands for Easier Testing

### ISSUE THREAD

**Issue by Guffawker** [muffeeee/midas-pro-series-osc-commands#5]
Finally got some time to sit down away from things to parse the data provided! I'm sure the JSON format helps w/ creating a companion module, but in an effort to help testing all of the commands and figuring out what they do I went ahead and converted all of the commands into OSC addresses so they can be easily copy/pasted or batch tested! I also created a QLab workspace with all of the commands imported as network cues and separated out into groups for each object. Not sure how helpful this is for folks but figured it might go a long way in helping the progress! I created a fork with the files available, and made a pull request to add them to the main branch if you want to! Next time I'm at the console I'll try to knock out as many as I can!

**Comment by muffeeee** [comment]
PR #4 merged. Thanks for the work!
